// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// anemometer_pulse //
// ---------------- //

#define anemometer_pulse_wrap_target 0
#define anemometer_pulse_wrap 2

static const uint16_t anemometer_pulse_program_instructions[] = {
            //     .wrap_target
    0x2032, //  0: wait   0 pin, 18                  
    0x20b2, //  1: wait   1 pin, 18                  
    0x0040, //  2: jmp    x--, 0                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program anemometer_pulse_program = {
    .instructions = anemometer_pulse_program_instructions,
    .length = 3,
    .origin = -1,
};

static inline pio_sm_config anemometer_pulse_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + anemometer_pulse_wrap_target, offset + anemometer_pulse_wrap);
    return c;
}
#endif

