// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------- //
// pulsecount //
// ---------- //

#define pulsecount_wrap_target 1
#define pulsecount_wrap 3

static const uint16_t pulsecount_program_instructions[] = {
    0xe021, //  0: set    x, 1                       
            //     .wrap_target
    0x2020, //  1: wait   0 pin, 0                   
    0x20a0, //  2: wait   1 pin, 0                   
    0x4021, //  3: in     x, 1                       
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulsecount_program = {
    .instructions = pulsecount_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config pulsecount_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulsecount_wrap_target, offset + pulsecount_wrap);
    return c;
}
#endif

