// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define MIN_PULSE_COUNT 3
#define PULSE_COUNT_BIT_SHIFT 2

// ---------- //
// pulsecount //
// ---------- //

#define pulsecount_wrap_target 1
#define pulsecount_wrap 7

static const uint16_t pulsecount_program_instructions[] = {
    0xe023, //  0: set    x, 3                       
            //     .wrap_target
    0x2021, //  1: wait   0 pin, 1                   
    0x20a1, //  2: wait   1 pin, 1                   
    0x00c5, //  3: jmp    pin, 5                     
    0x0001, //  4: jmp    1                          
    0x0041, //  5: jmp    x--, 1                     
    0xe023, //  6: set    x, 3                       
    0x4022, //  7: in     x, 2                       
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulsecount_program = {
    .instructions = pulsecount_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config pulsecount_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulsecount_wrap_target, offset + pulsecount_wrap);
    return c;
}
#endif

